export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import s from "./app.module.css"

export default function RootLayout({ children }) {
 return (
    <html lang="en">
        <body className={s.app}>{children}</body>
    </html>
 )
}
