export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import s from "./app.module.css"

export default function RootLayout({ children }) {
 return (
    <html lang="en">
    <head>
        <title>FILMS</title>
        <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet"/>
    </head>
    <body className={s.app}>{children}</body>
    </html>
 )
}
